# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go


publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit

  # Clients
  - name: "client" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Client" # Used in the UI, ie.: "New Post"
    folder: "_clients" # The path to the folder where the documents are stored
    sort: "order:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{order}}-{{slug}}"
    fields: # The fields each document in this collection have 
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Logo url", name: "logourl", widget: "image", required: true}
      - {label: "Description", name: "description", widget: "string", required: true} 
      - {label: "Order", name: "order", widget: "number", required: true}
      
   # Testimonials
  - name: "testimonial" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Testimonial" # Used in the UI, ie.: "New Post"
    folder: "_testimonials" # The path to the folder where the documents are stored
    sort: "order:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{order}}-{{name}}"
    fields: # The fields each document in this collection have 
      - {label: "Customer Name", name: "name", widget: "string", required: true}
      - {label: "Role", name: "role", widget: "string", required: true}
      - {label: "Company", name: "company", widget: "string", required: true}
      - {label: "Testimonial", name: "testimonial", widget: "string", required: true} 
      - {label: "Order", name: "order", widget: "number", required: true}

  # JOBS
  - name: "job" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Job" # Used in the UI, ie.: "New Post"
    folder: "_jobs" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "job"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}  
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: true}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true} 

  # Case studies 
  - name: "casestudies" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Case Study" # Used in the UI, ie.: "New Post"
    folder: "_casestudies" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "casestudy"}
      - {label: "Order", name: "order", widget: "number", required: true}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}  
      - {label: "Banner", name: "banner", widget: "image", required: true} 
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: true}
      - {label: "Description", name: "description", widget: "markdown", required: true}
      - {label: "Challenge", name: "challenge", widget: "markdown", required: true} 
      - {label: "Challenge Image", name: "challenge_imageurl", widget: "image", required: true} 
      - {label: "Solution", name: "solution", widget: "markdown", required: true} 
      - {label: "Solution Image", name: "solution_imageurl", widget: "image", required: true} 
      - {label: "Result", name: "result", widget: "markdown", required: true} 
      - {label: "Result Image", name: "result_imageurl", widget: "image", required: true} 
      - {label: "CTR", name: "ctr", widget: "string", required: true} 
      - {label: "CPA", name: "cpa", widget: "string", required: true} 
      - {label: "ROI", name: "roi", widget: "string", required: true} 

 

  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Banner Image", name: "banner", widget: "image", required: false}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "nicheBees", value: "nicheBees" } 
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
